version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd backend/to-do-list
      - sudo yum install maven
      - mvn clear install
      - sleep 60
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 368888336862.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t frolov-nikita-lab3 .
      - docker tag frolov-nikita-lab3:latest 368888336862.dkr.ecr.us-east-1.amazonaws.com/frolov-nikita-lab3:latest
      - docker push 368888336862.dkr.ecr.us-east-1.amazonaws.com/frolov-nikita-lab3:latest
      - aws register-task-definition --family frolov-nikita-lab03-td --container-definitions "[{\"name\":\"frolov-nikita-todo-be\",\"image\":\"368888336862.dkr.ecr.us-east-1.amazonaws.com/frolov-nikita-lab3:latest\",\"cpu\":1,\"memory\":0.75,\"essential\":true}]"
  post_build:
    commands:
      - echo Build completed on `date`
